name: Add merged pull request to current milestone

on:
  push:
    branches:
      - master

jobs:
  pr-merged:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Remove All Labels
        uses: actions/checkout@v2
        uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Pull Request Milestone
        uses: iyu/actions-milestone@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/milestone.yml

